### ISSUE TITLE
 complexity

### ISSUE THREAD

**Issue by shuvodas0** [shuvodas0/Searching-technique#1]
time and space complexity

**Comment by manish92596** [comment]
please assign it to me i can do it!.

**Comment by Kp-cloud371** [comment]
Please assign this issue to me

**Comment by manish92596** [comment]
Done

**Comment by Kp-cloud371** [comment]
Please assign this issue to me

**Comment by manish92596** [comment]
You failed to solve this problem. Can i help you???
Then why you write this ,please assign this issue to me..?
